[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:php-server]
command=php -S 0.0.0.0:8000 -t /var/www/gcore -d display_errors=1 -d error_reporting=E_ALL -d memory_limit=256M /var/www/gcore/docker/index.php
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/php.log
stderr_logfile=/var/log/supervisor/php-error.log
