#!/usr/bin/env php
<?php
/**
 * gCore Config Compiler
 *
 * Parses YAML config files, resolves environment variables, and writes
 * a compiled PHP array to config/compiled.php. This eliminates YAML
 * parsing on every request — the compiled file is OPcache'd by PHP.
 *
 * Run at deploy time:
 *   php scripts/compile-config.php
 *
 * The compiled file is gitignored and regenerated on each deploy.
 *
 * @package gCore
 */

// Load environment files (same as bootstrap.php)
$envFiles = [
    '/etc/geodineum/bootstrap.env',
    '/etc/geodineum/components/gCore/gcore.env',
];

foreach ($envFiles as $envFile) {
    if (file_exists($envFile) && is_readable($envFile)) {
        $content = file_get_contents($envFile);
        if ($content === false) continue;
        foreach (explode("\n", $content) as $line) {
            $line = trim($line);
            if ($line === '' || strpos($line, '#') === 0) continue;
            if (strpos($line, 'export ') === 0) $line = substr($line, 7);
            if (preg_match('/^([A-Z_][A-Z0-9_]*)=(.*)$/i', $line, $matches)) {
                $name = $matches[1];
                $value = $matches[2];
                if ((strpos($value, '"') === 0 && substr($value, -1) === '"') ||
                    (strpos($value, "'") === 0 && substr($value, -1) === "'")) {
                    $value = substr($value, 1, -1);
                }
                $value = preg_replace_callback('/\$\{([A-Z_][A-Z0-9_]*)\}/i', function($m) {
                    return getenv($m[1]) ?: '';
                }, $value);
                if (getenv($name) === false) {
                    putenv("$name=$value");
                }
            }
        }
    }
}

// Resolve base path
$basePath = getenv('GCORE_BASE_PATH') ?: '/opt/geodineum/gCore';
if (!is_dir($basePath)) {
    $basePath = dirname(__DIR__);
}
$configPath = $basePath . '/config';

// Check for yaml extension
if (!function_exists('yaml_parse_file')) {
    fwrite(STDERR, "ERROR: php-yaml extension required. Install: apt install php-yaml\n");
    exit(1);
}

/**
 * Recursively resolve ${VAR:-default} environment variable references
 */
function resolveEnvVars($data) {
    if (is_array($data)) {
        foreach ($data as $key => $value) {
            $data[$key] = resolveEnvVars($value);
        }
        return $data;
    }

    if (!is_string($data) || strpos($data, '${') === false) {
        return $data;
    }

    return preg_replace_callback('/\$\{([^}]+)\}/', function ($matches) {
        $expr = $matches[1];
        if (strpos($expr, ':-') !== false) {
            [$varName, $default] = explode(':-', $expr, 2);
            $env = getenv($varName);
            return ($env !== false && $env !== '') ? $env : $default;
        }
        $env = getenv($expr);
        return ($env !== false) ? $env : $matches[0];
    }, $data);
}

// Parse config files
$configs = [];
$files = [
    'default' => $configPath . '/default.yaml',
    'services' => $configPath . '/services.yaml',
];

foreach ($files as $name => $file) {
    if (!file_exists($file)) {
        fwrite(STDERR, "WARNING: Config file not found: {$file}\n");
        continue;
    }

    $data = yaml_parse_file($file);
    if ($data === false) {
        fwrite(STDERR, "ERROR: Failed to parse YAML: {$file}\n");
        exit(1);
    }

    $configs[$name] = resolveEnvVars($data);
    fwrite(STDOUT, "  Compiled: {$name} (" . count($data) . " top-level keys)\n");
}

if (empty($configs)) {
    fwrite(STDERR, "ERROR: No config files found in {$configPath}\n");
    exit(1);
}

// Build the compiled output
$timestamp = date('Y-m-d H:i:s');
$defaultMtime = file_exists($files['default']) ? filemtime($files['default']) : 0;
$servicesMtime = file_exists($files['services']) ? filemtime($files['services']) : 0;
$versionHash = md5($defaultMtime . ':' . $servicesMtime);

$compiled = [
    '_compiled' => [
        'timestamp' => $timestamp,
        'version_hash' => $versionHash,
        'source_mtimes' => [
            'default.yaml' => $defaultMtime,
            'services.yaml' => $servicesMtime,
        ],
    ],
    'default' => $configs['default'] ?? [],
    'services' => $configs['services'] ?? [],
];

// Write compiled PHP file
$outputFile = $configPath . '/compiled.php';
$phpCode = "<?php\n";
$phpCode .= "/**\n";
$phpCode .= " * gCore Compiled Configuration\n";
$phpCode .= " *\n";
$phpCode .= " * AUTO-GENERATED by scripts/compile-config.php — DO NOT EDIT\n";
$phpCode .= " * Generated: {$timestamp}\n";
$phpCode .= " * Version: {$versionHash}\n";
$phpCode .= " *\n";
$phpCode .= " * Source files:\n";
$phpCode .= " *   config/default.yaml  (mtime: {$defaultMtime})\n";
$phpCode .= " *   config/services.yaml (mtime: {$servicesMtime})\n";
$phpCode .= " */\n";
$phpCode .= "return " . var_export($compiled, true) . ";\n";

if (file_put_contents($outputFile, $phpCode) === false) {
    fwrite(STDERR, "ERROR: Failed to write compiled config to {$outputFile}\n");
    exit(1);
}

// Set proper permissions (readable by www-data group)
chmod($outputFile, 0640);

fwrite(STDOUT, "\n  Written: {$outputFile}\n");
fwrite(STDOUT, "  Version: {$versionHash}\n");
fwrite(STDOUT, "  Size:    " . number_format(filesize($outputFile)) . " bytes\n");

// Invalidate OPcache for the compiled file if running under FPM
if (function_exists('opcache_invalidate')) {
    opcache_invalidate($outputFile, true);
    fwrite(STDOUT, "  OPcache invalidated\n");
}

// Invalidate APCu config cache if available
if (function_exists('apcu_delete')) {
    apcu_delete('gcore:config:default');
    apcu_delete('gcore:config:services');
    fwrite(STDOUT, "  APCu cache cleared\n");
}

// =========================================================================
// Store compiled config in ValKey per-site (canonical source for runtime)
// =========================================================================
// Each site gets its own copy under {site_id}:gcore:config:*
// This enables:
//   - Multi-server config distribution (all servers read from ValKey)
//   - Runtime config overrides via admin panel
//   - Per-site config customization
// =========================================================================

$valkeyHost = getenv('VALKEY_HOST') ?: '127.0.0.1';
$valkeyPort = (int)(getenv('VALKEY_PORT') ?: 47445);

// discover site IDs from the per-site directory layout. Each
// registered site has /etc/geodineum/sites/<site_id>/valkey_client.password
// — replaces the previously flat layout
// /etc/geodineum/credentials/valkey_client_<id>.password. We support
// BOTH locations during the migration window (any file present in
// either layout wins, new layout takes precedence on duplicates).
$siteIds = [];

// New layout: /etc/geodineum/sites/<id>/valkey_client.password
foreach (glob('/etc/geodineum/sites/*/valkey_client.password') as $f) {
    if (preg_match('#/sites/([^/]+)/valkey_client\.password$#', $f, $m)) {
        $siteIds[$m[1]] = $f;
    }
}

// Legacy layout (only if site_id isn't already covered by new layout)
$legacyCredFiles = glob('/etc/geodineum/credentials/valkey_client_*.password');
foreach ($legacyCredFiles as $f) {
    $basename = basename($f, '.password');
    if (preg_match('/^valkey_client_(.+)$/', $basename, $m)) {
        if ($m[1] !== '' && !isset($siteIds[$m[1]])) {
            $siteIds[$m[1]] = $f;
        }
    }
}

// Explicit site ID override via argument or env
$explicitSiteId = getenv('GCORE_SITE_ID') ?: ($argv[1] ?? null);
if ($explicitSiteId && !isset($siteIds[$explicitSiteId])) {
    // Try new location first, then legacy.
    $newPath = "/etc/geodineum/sites/{$explicitSiteId}/valkey_client.password";
    $legacyPath = "/etc/geodineum/credentials/valkey_client_{$explicitSiteId}.password";
    if (file_exists($newPath)) {
        $siteIds[$explicitSiteId] = $newPath;
    } elseif (file_exists($legacyPath)) {
        $siteIds[$explicitSiteId] = $legacyPath;
    }
}

if (!empty($siteIds) && extension_loaded('redis')) {
    fwrite(STDOUT, "\n  Storing to ValKey per-site:\n");

    foreach ($siteIds as $siteId => $credFile) {
        try {
            $redis = new Redis();
            $redis->pconnect($valkeyHost, $valkeyPort, 2.0);

            // Authenticate with per-site ACL user
            $password = trim(file_get_contents($credFile));
            $aclUser = 'gnode_client_' . $siteId;
            $redis->auth([$aclUser, $password]);

            // Store default config — hash-tagged for cluster co-location
            // (per-site config keys must hash-tag
            // so default + services + _meta + constellation:generation
            // all live on the same shard, matching ecosystem convention).
            $defaultKey = '{' . $siteId . '}:gcore:config:default';
            $redis->set($defaultKey, json_encode($configs['default'] ?? []));

            // Store services topology (canonical source)
            $servicesKey = '{' . $siteId . '}:gcore:config:services';
            $redis->set($servicesKey, json_encode($configs['services'] ?? []));

            // Store metadata
            $metaKey = '{' . $siteId . '}:gcore:config:_meta';
            $redis->set($metaKey, json_encode([
                'compiled_at' => $timestamp,
                'version_hash' => $versionHash,
                'source_mtimes' => [
                    'default.yaml' => $defaultMtime,
                    'services.yaml' => $servicesMtime,
                ],
            ]));

            // Increment constellation generation (signals APCu staleness across all nodes)
            $genKey = '{' . $siteId . '}:constellation:generation';
            $newGen = $redis->incr($genKey);

            // Broadcast config_updated (within site ACL scope)
            try {
                $broadcastKey = '{' . $siteId . '}:constellation:broadcast';
                $redis->xAdd($broadcastKey, '*', [
                    't' => 'config_updated',
                    'ss' => $siteId,
                    'gen' => (string)$newGen,
                    'vh' => $versionHash,
                    'ts' => (string)(time() * 1000),
                ]);
                $redis->xTrim($broadcastKey, 100, true);
            } catch (\Throwable $broadcastErr) {
                // Broadcast failure is non-fatal — generation counter is sufficient
            }

            fwrite(STDOUT, "    {$siteId}: 3 keys stored, generation {$newGen} (user: {$aclUser})\n");

        } catch (\Throwable $e) {
            fwrite(STDERR, "    {$siteId}: FAILED — {$e->getMessage()}\n");
        }
    }
} else {
    if (empty($siteIds)) {
        fwrite(STDOUT, "\n  ValKey: No site credentials found, skipping ValKey storage\n");
    } else {
        fwrite(STDOUT, "\n  ValKey: redis extension not loaded, skipping ValKey storage\n");
    }
}

fwrite(STDOUT, "\n  Config compiled successfully.\n\n");
